const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Sprite,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt
	];
};
self.C3_JsPropNameTable = [
	{文本: 0},
	{觸控: 0},
	{文本2: 0},
	{正弦運動: 0},
	{文本3: 0},
	{文本4: 0},
	{isCorrect: 0},
	{box: 0},
	{精靈: 0},
	{文本5: 0},
	{音頻: 0},
	{文本6: 0},
	{精靈2: 0},
	{精靈3: 0},
	{文本7: 0},
	{精靈4: 0},
	{精靈5: 0},
	{文本8: 0},
	{精靈6: 0},
	{精靈7: 0},
	{文本9: 0},
	{精靈8: 0},
	{精靈9: 0},
	{文本10: 0},
	{時間: 0},
	{Countdown: 0},
	{GameTimer: 0},
	{GameTime: 0}
];

self.InstanceType = {
	文本: class extends self.ITextInstance {},
	觸控: class extends self.IInstance {},
	文本2: class extends self.ITextInstance {},
	文本3: class extends self.ITextInstance {},
	文本4: class extends self.ITextInstance {},
	box: class extends self.ISpriteInstance {},
	精靈: class extends self.ISpriteInstance {},
	文本5: class extends self.ITextInstance {},
	音頻: class extends self.IInstance {},
	文本6: class extends self.ITextInstance {},
	精靈2: class extends self.ISpriteInstance {},
	精靈3: class extends self.ISpriteInstance {},
	文本7: class extends self.ITextInstance {},
	精靈4: class extends self.ISpriteInstance {},
	精靈5: class extends self.ISpriteInstance {},
	文本8: class extends self.ITextInstance {},
	精靈6: class extends self.ISpriteInstance {},
	精靈7: class extends self.ISpriteInstance {},
	文本9: class extends self.ITextInstance {},
	精靈8: class extends self.ISpriteInstance {},
	精靈9: class extends self.ISpriteInstance {},
	文本10: class extends self.ITextInstance {},
	時間: class extends self.ITextInstance {}
}